# Generated by Django 5.0.6 on 2024-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Tag',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Article',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=100)),
        #         ('tags', models.ManyToManyField(to='student.tag')),
        #     ],
        # ),
    ]
