# Generated by Django 5.0.6 on 2024-05-26 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_tag_article'),
    ]

    operations = [
        
        # migrations.CreateModel(
            # name='SubTopic',
            # fields=[
            #     ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #     ('name', models.CharField(max_length=100)),
            #     ('description', models.TextField()),
            #     ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.topic')),
            # ],
        
    ]
