# Generated by Django 5.0.6 on 2024-05-26 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_topic_feedback_remove_topic_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opening',
            options={'ordering': ['-added_on']},
        ),
        migrations.AddField(
            model_name='opening',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
