# Generated by Django 5.0.6 on 2024-05-29 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_interview_date_alter_opening_added_on'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
    ]
