# Generated by Django 5.0.6 on 2024-05-29 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_interview_date_alter_opening_added_on'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='InterviewQuestions',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('que', models.CharField(max_length=300, null=True)),
        #         ('ans', models.TextField(max_length=1500, null=True)),
        #     ],
        #     options={
        #         'db_table': 'interviewQuestions',
        #     },
        # ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 13, 22, 8, 4474, tzinfo=datetime.timezone.utc)),
        )
        # migrations.AlterField(
        #     model_name='opening',
        #     name='added_on',
        #     field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 13, 22, 8, 4474, tzinfo=datetime.timezone.utc)),
        # ),
    ]
