# Generated by Django 5.0.6 on 2024-05-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_interviewquestions_alter_interview_date_and_more - Copy'),
        ('student', '0030_interviewquestions_alter_interview_date_and_more'),
    ]

    operations = [
    ]
