# Generated by Django 5.0.6 on 2024-05-30 15:10

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_merge_20240530_0107'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='progress',
            field=models.CharField(max_length=50, null=True),
        ),
        # migrations.AlterField(
        #     model_name='opening',
        #     name='company_name',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='opening',
        #     name='logo',
        #     field=models.ImageField(blank=True, null=True, upload_to=''),
        # ),
        # migrations.AlterField(
        #     model_name='opening',
        #     name='role',
        #     field=models.CharField(max_length=30, null=True),
        # ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guardian',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        # migrations.AlterModelTable(
        #     name='profile',
        #     table=student.models.opening,
        # ),
        
    ]
