# Generated by Django 5.0.6 on 2024-05-30 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_remove_subtopic_topic_alter_opening_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, null=True)),
                ('salary', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'openings',
            },
        ),
        # migrations.RemoveField(
        #     model_name='article',
        #     name='tags',
        # ),
        # migrations.DeleteModel(
        #     name='opening',
        # ),
        # migrations.RemoveField(
        #     model_name='subtopic',
        #     name='topic',
        # ),
        # migrations.RenameField(
        #     model_name='profile',
        #     old_name='emergency',
        #     new_name='contact',
        # ),
        # migrations.RemoveField(
        #     model_name='interview',
        #     name='date',
        # ),
        # migrations.RemoveField(
        #     model_name='interviewquestions',
        #     name='que',
        # ),
        # migrations.AddField(
        #     model_name='interview',
        #     name='link',
        #     field=models.CharField(max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='interviewquestions',
        #     name='ques',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='Article',
        # ),
        # migrations.DeleteModel(
        #     name='Tag',
        # ),
        # migrations.DeleteModel(
        #     name='SubTopic',
        # ),
        # migrations.DeleteModel(
        #     name='Topic',
        # ),
    ]
