# Generated by Django 5.0.6 on 2024-05-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_openings_remove_article_tags_delete_opening_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='openings',
            table='openings',
        ),
    ]
