# Generated by Django 5.0.6 on 2024-06-07 10:54

# import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_studymaterial'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='studymaterial',
    #         name='content',
    #         field=markdownx.models.MarkdownxField(),
    #     ),
    # ]
