# Generated by Django 5.0.6 on 2024-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_alter_studymaterial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
