# Generated by Django 5.0.6 on 2024-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_studymaterial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='content',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
