# Generated by Django 5.0.6 on 2024-06-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_studytopic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyTopic',
        ),
    ]
