# Generated by Django 5.0.6 on 2024-06-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_studytopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='studytopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studytopic'),
        ),
    ]
