# Generated by Django 5.0.6 on 2024-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0048_subtopicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='material_id',
            field=models.IntegerField(null=True),
        ),
    ]
