# Generated by Django 5.0.6 on 2024-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_studymaterial_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytopic',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.module'),
            preserve_default=False,
        ),
    ]
