# Generated by Django 4.2.13 on 2024-06-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_course_price'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='interviewquestions',
    #         name='moduleName',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.interview'),
    #         preserve_default=False,
    #     ),
    # ]
