# Generated by Django 4.2.13 on 2024-06-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursecategories')),
            ],
            options={
                'db_table': 'courseSubcategory',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.coursesubcategory'),
            preserve_default=False,
        ),
    ]
