# Generated by Django 4.2.13 on 2024-06-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_coursesubcategory_course_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.coursecategories'),
            preserve_default=False,
        ),
    ]
