# Generated by Django 4.2.13 on 2024-06-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
