# Generated by Django 4.2.13 on 2024-06-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_interviewquestions_modulename'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='interviewquestions',
    #         old_name='modulename',
    #         new_name='moduleName',
    #     ),
    # ]
