# Generated by Django 4.2.13 on 2024-06-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_delete_interviewquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100, null=True)),
                ('ans', models.CharField(max_length=1500, null=True)),
                ('moduleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.interview')),
            ],
            options={
                'db_table': 'interviewQuestions',
            },
        ),
    ]
