# Generated by Django 4.2.13 on 2024-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
