# Generated by Django 4.2.13 on 2024-06-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0067_profile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
