# Generated by Django 5.0.6 on 2024-07-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_remove_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
